language: node_js
node_js:
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
env:
  matrix:
    - RAVENDB_TEST_SERVER_PATH=./RavenDB/Server/Raven.Server
      RAVENDB_TEST_SERVER_CERTIFICATE_PATH=./certs/server.pfx
      RAVENDB_TEST_CLIENT_CERT_PASSPHRASE=client11
      RAVENDB_TEST_CLIENT_CERT_PATH=./certs/nodejs.pem
      RAVENDB_TEST_CA_PATH=/usr/local/share/ca-certificates/ca.crt
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libunwind8 wget libicu52 libssl-dev curl unzip gettext libcurl4-openssl-dev zlib1g uuid-dev bzip2 openssl
  - wget -O RavenDB.tar.bz2 https://hibernatingrhinos.com/downloads/RavenDB%20for%20Linux%20x64/latest?buildType=nightly
  - tar xjf RavenDB.tar.bz2
  - mkdir certs; pushd certs
  - openssl genrsa -out ca.key 2048
  - openssl req -new -x509 -key ca.key -out ca.crt -subj "/C=US/ST=Arizona/L=Nevada/O=RavenDB Test CA/OU=RavenDB test CA/CN=localhost/emailAddress=ravendbca@example.com"
  - openssl genrsa -out localhost.key 2048
  - openssl req -new  -key localhost.key -out localhost.csr -subj "/C=US/ST=Arizona/L=Nevada/O=RavenDB Test/OU=RavenDB test/CN=localhost/emailAddress=ravendb@example.com"
  - openssl x509 -req -extensions ext -extfile ../test/Assets/test_cert.conf -in localhost.csr -CA ca.crt -CAkey ca.key -CAcreateserial -out localhost.crt
  - cat localhost.key localhost.crt > nodejs.pem
  - openssl pkcs12 -passout pass:$RAVENDB_CLIENT_CERT_PASSPHRASE -export -out server.pfx -inkey localhost.key -in localhost.crt
  - sudo cp ca.crt /usr/local/share/ca-certificates/ca.crt
  - sudo update-ca-certificates
  - popd
  - pwd && ls  